import Head from "next/head";

import BaseTemplate from "@/components/template/BaseTemplate";
import TemplateContainer from "@/containers/template/TemplateContainer";

export default function TEMPLATE() {
  return (
    <>
      <Head>
        <title>TEMPLATE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseTemplate>
        <TemplateContainer/>
      </BaseTemplate>
    </>
  );
}
