import Head from "next/head";

import BaseTemplate from "@/components/template/BaseTemplate";

export default function Module() {
  return (
    <>
      <Head>
        <title>Module</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseTemplate>
        <></>
      </BaseTemplate>
    </>
  );
}
